/**
 * 
 */
package com.felipem.euler.problema012;

/**
 * @author felipem ( http://felipem.com )
 *
 */
public class Problema012 {

	/**
	 * 
	 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
	 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
	 * 
	 * Let us list the factors of the first seven triangle numbers:
	 * 1: 1
	 * 3: 1,3
	 * 6: 1,2,3,6
	 * 10: 1,2,5,10
	 * 15: 1,3,5,15
	 * 21: 1,3,7,21
	 * 28: 1,2,4,7,14,28
	 * 
	 * We can see that 28 is the first triangle number to have over five divisors.
	 * What is the value of the first triangle number to have over five hundred divisors?
	 * 
	 * La secuencia de los números triangulares es generada mediante la suma de los números naturales. De este modo, el séptimo número triangular sería 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. Los primeros diez términos de la secuencia serían:
	 *
	 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
	 * 
	 * Vamos a enumerar los factores de los siete primeros números triangulares:
	 * 
	 * 1 : 1
	 * 3 : 1,3
	 * 6 : 1,2,3,6
	 * 10 : 1,2,5,10
	 * 15 : 1,3,5,15
	 * 21 : 1,3,7,21
	 * 28 : 1,2,4,7,14,28
	 * 
	 * Podemos ver que el 28 es el primer número triangular en tener más de cinco divisores.
	 * ¿Cuál es el valor del primer número triangular en tener más de 500 divisores?
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
